global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          __metrics_path__: /metrics

  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:15692"]

